basePath: /
definitions:
  schema.Demo:
    properties:
      code:
        description: 编号
        type: string
      created_at:
        description: 创建时间
        type: string
      creator:
        description: 创建者
        type: string
      memo:
        description: 备注
        type: string
      name:
        description: 名称
        type: string
      record_id:
        description: 记录ID
        type: string
      status:
        description: 状态(1:启用 2:停用)
        type: integer
    required:
    - code
    - name
    - status
    type: object
  schema.HTTPError:
    properties:
      error:
        $ref: '#/definitions/schema.HTTPErrorItem'
        description: 错误项
        type: object
    type: object
  schema.HTTPErrorItem:
    properties:
      code:
        description: 错误码
        type: integer
      message:
        description: 错误信息
        type: string
    type: object
  schema.HTTPStatus:
    properties:
      status:
        description: 状态(OK)
        type: string
    type: object
host: 127.0.0.1:10088
info:
  contact:
    email: tiannianshou@gmail.com
    name: LyricTian
  description: RBAC scaffolding based on Gin + Gorm + Dig.
  license: {}
  title: GinAdmin
  version: v1.0.0-core
paths:
  /api/v1/demos:
    get:
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - default: 1
        description: 分页索引
        in: query
        name: current
        required: true
        type: integer
      - default: 10
        description: 分页大小
        in: query
        name: pageSize
        required: true
        type: integer
      - description: 编号
        in: query
        name: code
        type: string
      - description: 名称
        in: query
        name: name
        type: string
      - description: 状态(1:启用 2:停用)
        in: query
        name: status
        type: integer
      responses:
        "200":
          description: 查询结果：{list:列表数据,pagination:{current:页索引,pageSize:页大小,total:总数量}}
          schema:
            items:
              $ref: '#/definitions/schema.Demo'
            type: array
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.HTTPError'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.HTTPError'
      summary: 查询数据
      tags:
      - Demo
    post:
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 创建数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.Demo'
          type: object
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.Demo'
        "400":
          description: '{error:{code:0,message:无效的请求参数}}'
          schema:
            $ref: '#/definitions/schema.HTTPError'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.HTTPError'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.HTTPError'
      summary: 创建数据
      tags:
      - Demo
  /api/v1/demos/{id}:
    delete:
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 记录ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{status:OK}'
          schema:
            $ref: '#/definitions/schema.HTTPStatus'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.HTTPError'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.HTTPError'
      summary: 删除数据
      tags:
      - Demo
    get:
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 记录ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.Demo'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.HTTPError'
        "404":
          description: '{error:{code:0,message:资源不存在}}'
          schema:
            $ref: '#/definitions/schema.HTTPError'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.HTTPError'
      summary: 查询指定数据
      tags:
      - Demo
    put:
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 记录ID
        in: path
        name: id
        required: true
        type: string
      - description: 更新数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.Demo'
          type: object
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.Demo'
        "400":
          description: '{error:{code:0,message:无效的请求参数}}'
          schema:
            $ref: '#/definitions/schema.HTTPError'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.HTTPError'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.HTTPError'
      summary: 更新数据
      tags:
      - Demo
  /api/v1/demos/{id}/disable:
    patch:
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 记录ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{status:OK}'
          schema:
            $ref: '#/definitions/schema.HTTPStatus'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.HTTPError'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.HTTPError'
      summary: 禁用数据
      tags:
      - Demo
  /api/v1/demos/{id}/enable:
    patch:
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 记录ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{status:OK}'
          schema:
            $ref: '#/definitions/schema.HTTPStatus'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.HTTPError'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.HTTPError'
      summary: 启用数据
      tags:
      - Demo
schemes:
- http
- https
swagger: "2.0"
